name: Run Streamlit App

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main, master ]  # Auto-trigger on push
  pull_request:
    branches: [ main, master ]

env:
  GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
  SERP_API_KEY: ${{ secrets.SERP_API_KEY }}

jobs:
  test-streamlit-app:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Streamlit app (test mode)
        run: |
          timeout 30s streamlit run main.py --server.headless true --server.port 8501 || true
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          SERP_API_KEY: ${{ secrets.SERP_API_KEY }}